-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-05-28 21:45:59 CEST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE kategorie 
    ( 
     id_kategorie NUMBER  NOT NULL , 
     nazev        VARCHAR2 (100)  NOT NULL , 
     popis        VARCHAR2 (255) 
    ) 
    LOGGING 
;

ALTER TABLE kategorie 
    ADD CONSTRAINT kategorie_PK PRIMARY KEY ( id_kategorie ) ;

CREATE TABLE objednavka 
    ( 
     id_objednavka    NUMBER  NOT NULL , 
     datum_vytvoreni  DATE  NOT NULL , 
     stav             VARCHAR2 (20)  NOT NULL , 
     celkova_cena     NUMBER (10,2) , 
     jmeno_zadavatele VARCHAR2 (100)  NOT NULL , 
     zpusob_platby    VARCHAR2 (50) , 
     zpusob_dopravy   VARCHAR2 (50) , 
     id_prodejna      NUMBER 
    ) 
    LOGGING 
;

ALTER TABLE objednavka 
    ADD CONSTRAINT objednavka_PK PRIMARY KEY ( id_objednavka ) ;

CREATE TABLE polozka_objednavky 
    ( 
     id_polozka     NUMBER  NOT NULL , 
     id_objednavka  NUMBER , 
     id_produkt     NUMBER , 
     mnozstvi       NUMBER , 
     cena_za_kus    NUMBER (10,2) , 
     sleva_procenta NUMBER (5,2) 
    ) 
    LOGGING 
;

ALTER TABLE polozka_objednavky 
    ADD CONSTRAINT polozka_objednavky_PK PRIMARY KEY ( id_polozka ) ;

CREATE TABLE prodejna 
    ( 
     id_prodejna     NUMBER  NOT NULL , 
     nazev           VARCHAR2 (100)  NOT NULL , 
     mesto           VARCHAR2 (100)  NOT NULL , 
     adresa          VARCHAR2 (150)  NOT NULL , 
     oteviraci_doba  VARCHAR2 (100) , 
     velikost_skladu NUMBER 
    ) 
    LOGGING 
;

ALTER TABLE prodejna 
    ADD CONSTRAINT prodejna_PK PRIMARY KEY ( id_prodejna ) ;

CREATE TABLE prodejna_produkt 
    ( 
     id_prodejna    NUMBER  NOT NULL , 
     id_produkt     NUMBER  NOT NULL , 
     mnozstvi       NUMBER , 
     umisteni_regal VARCHAR2 (20) 
    ) 
    LOGGING 
;

ALTER TABLE prodejna_produkt 
    ADD CONSTRAINT prodejna_produkt_PK PRIMARY KEY ( id_prodejna, id_produkt ) ;

CREATE TABLE produkt 
    ( 
     id_produkt    NUMBER  NOT NULL , 
     kod_produktu  VARCHAR2 (50)  NOT NULL , 
     nazev         VARCHAR2 (100)  NOT NULL , 
     popis         VARCHAR2 (500) , 
     cena          NUMBER (10,2)  NOT NULL , 
     skladem       NUMBER , 
     zaruka_mesice NUMBER , 
     datum_uvedeni DATE , 
     id_kategorie  NUMBER , 
     id_vyrobce    NUMBER 
    ) 
    LOGGING 
;

ALTER TABLE produkt 
    ADD CONSTRAINT produkt_PK PRIMARY KEY ( id_produkt ) ;

CREATE TABLE vyrobce 
    ( 
     id_vyrobce     NUMBER  NOT NULL , 
     nazev          VARCHAR2 (100)  NOT NULL , 
     zeme_puvodu    VARCHAR2 (100) , 
     rok_zalozeni   NUMBER , 
     webova_stranka VARCHAR2 (150) 
    ) 
    LOGGING 
;

ALTER TABLE vyrobce 
    ADD CONSTRAINT vyrobce_PK PRIMARY KEY ( id_vyrobce ) ;

CREATE TABLE zamestnanec 
    ( 
     id_zamestnanec NUMBER  NOT NULL , 
     jmeno          VARCHAR2 (50)  NOT NULL , 
     prijmeni       VARCHAR2 (50)  NOT NULL , 
     pozice         VARCHAR2 (50) , 
     plat           NUMBER (10,2) , 
     datum_nastupu  DATE , 
     smena          VARCHAR2 (20) , 
     id_prodejna    NUMBER 
    ) 
    LOGGING 
;

ALTER TABLE zamestnanec 
    ADD CONSTRAINT zamestnanec_PK PRIMARY KEY ( id_zamestnanec ) ;

ALTER TABLE objednavka 
    ADD CONSTRAINT objednavka_prodejna_FK FOREIGN KEY 
    ( 
     id_prodejna
    ) 
    REFERENCES prodejna 
    ( 
     id_prodejna
    ) 
    NOT DEFERRABLE 
;

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE polozka_objednavky 
    ADD CONSTRAINT polozka_objednavky_objednavka_FK FOREIGN KEY 
    ( 
     id_objednavka
    ) 
    REFERENCES objednavka 
    ( 
     id_objednavka
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE polozka_objednavky 
    ADD CONSTRAINT polozka_objednavky_produkt_FK FOREIGN KEY 
    ( 
     id_produkt
    ) 
    REFERENCES produkt 
    ( 
     id_produkt
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE prodejna_produkt 
    ADD CONSTRAINT prodejna_produkt_prodejna_FK FOREIGN KEY 
    ( 
     id_prodejna
    ) 
    REFERENCES prodejna 
    ( 
     id_prodejna
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE prodejna_produkt 
    ADD CONSTRAINT prodejna_produkt_produkt_FK FOREIGN KEY 
    ( 
     id_produkt
    ) 
    REFERENCES produkt 
    ( 
     id_produkt
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE produkt 
    ADD CONSTRAINT produkt_kategorie_FK FOREIGN KEY 
    ( 
     id_kategorie
    ) 
    REFERENCES kategorie 
    ( 
     id_kategorie
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE produkt 
    ADD CONSTRAINT produkt_vyrobce_FK FOREIGN KEY 
    ( 
     id_vyrobce
    ) 
    REFERENCES vyrobce 
    ( 
     id_vyrobce
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE zamestnanec 
    ADD CONSTRAINT zamestnanec_prodejna_FK FOREIGN KEY 
    ( 
     id_prodejna
    ) 
    REFERENCES prodejna 
    ( 
     id_prodejna
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE produkt
ADD CONSTRAINT chk_cena
CHECK (cena > 0);

ALTER TABLE produkt
ADD CONSTRAINT chk_skladem
CHECK (skladem >= 0);

ALTER TABLE objednavka
ADD CONSTRAINT chk_stav
CHECK (stav IN ('nova', 'zaplacena', 'odeslana', 'stornovana'));

ALTER TABLE zamestnanec
ADD CONSTRAINT chk_plat
CHECK (plat > 0);



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             16
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0
