--Create wf_currencies table
CREATE TABLE  WF_CURRENCIES 
   ("CURRENCY_CODE" VARCHAR2(7), 
	"CURRENCY_NAME" VARCHAR2(40) CONSTRAINT "WF_CURR_NN" NOT NULL ENABLE, 
	"COMMENTS" VARCHAR2(150), 
	CONSTRAINT "WF_CURR_PK" PRIMARY KEY ("CURRENCY_CODE")
	USING INDEX  ENABLE
   );

-- Create wf_languages table
CREATE TABLE  WF_LANGUAGES
   ("LANGUAGE_ID" NUMBER(4,0), 
	"LANGUAGE_NAME" VARCHAR2(50) CONSTRAINT "WF_LANG_LANGNAME_NN" NOT NULL ENABLE, 
	CONSTRAINT "WF_LANG_PK" PRIMARY KEY ("LANGUAGE_ID")
	USING INDEX  ENABLE
   );

--Create wf_world_regions table
CREATE TABLE  WF_WORLD_REGIONS
   ("REGION_ID" NUMBER(3,0), 
	"REGION_NAME" VARCHAR2(35) CONSTRAINT "WF_REG_REGNAME_NN" NOT NULL ENABLE, 
	CONSTRAINT "WF_REG_PK" PRIMARY KEY ("REGION_ID")
	USING INDEX  ENABLE
   );

-- Create wf_countries table
CREATE TABLE  WF_COUNTRIES
   ("COUNTRY_ID" NUMBER(4,0), 
	"REGION_ID" NUMBER(3,0) NOT NULL ENABLE, 
	"COUNTRY_NAME" VARCHAR2(70) CONSTRAINT "WF_CNAME_NN" NOT NULL ENABLE, 
	"COUNTRY_TRANSLATED_NAME" VARCHAR2(40), 
	"LOCATION" VARCHAR2(90), 
	"CAPITOL" VARCHAR2(50), 
	"AREA" NUMBER(15,0), 
	"COASTLINE" NUMBER(8,0), 
	"LOWEST_ELEVATION" NUMBER(6,0), 
	"LOWEST_ELEV_NAME" VARCHAR2(70), 
	"HIGHEST_ELEVATION" NUMBER(6,0), 
	"HIGHEST_ELEV_NAME" VARCHAR2(50), 
	"DATE_OF_INDEPENDENCE" VARCHAR2(30), 
	"NATIONAL_HOLIDAY_NAME" VARCHAR2(200), 
	"NATIONAL_HOLIDAY_DATE" VARCHAR2(30), 
	"POPULATION" NUMBER(12,0), 
	"POPULATION_GROWTH_RATE" VARCHAR2(10), 
	"LIFE_EXPECT_AT_BIRTH" NUMBER(6,2), 
	"MEDIAN_AGE" NUMBER(6,2), 
	"AIRPORTS" NUMBER(6,0), 
	"CLIMATE" VARCHAR2(1000), 
	"FIPS_ID" CHAR(2), 
	"INTERNET_EXTENSION" VARCHAR2(3), 
	"FLAG" BLOB, 
	"CURRENCY_CODE" VARCHAR2(7) NOT NULL ENABLE, 
	CONSTRAINT "WF_CRTY_PK" PRIMARY KEY ("COUNTRY_ID")
	USING INDEX  ENABLE
   );
   
-- Add FK constraints
ALTER TABLE  WF_COUNTRIES ADD CONSTRAINT "WF_REGION_ID_FK1" FOREIGN KEY ("REGION_ID")
	REFERENCES  WF_WORLD_REGIONS ("REGION_ID") ENABLE;

CREATE INDEX  "WF_CTRY_REG_IDX" ON  WF_COUNTRIES ("REGION_ID");

ALTER TABLE  WF_COUNTRIES ADD CONSTRAINT "WF_CURR_ID_FK2" FOREIGN KEY ("CURRENCY_CODE")
	REFERENCES  WF_CURRENCIES ("CURRENCY_CODE") ENABLE;

CREATE INDEX  "WF_CTRY_CURR_IDX" ON  WF_COUNTRIES ("CURRENCY_CODE");

-- Create wf_spoken_languages table
CREATE TABLE  WF_SPOKEN_LANGUAGES
   ("COUNTRY_ID" NUMBER(4,0), 
	"LANGUAGE_ID" NUMBER(4,0), 
	"OFFICIAL" VARCHAR2(2), 
	"COMMENTS" VARCHAR2(512), 
	CONSTRAINT "WF_SPOKEN_LANG_PK" PRIMARY KEY ("COUNTRY_ID", "LANGUAGE_ID")
	USING INDEX  ENABLE
   );
-- Add FK constraints
ALTER TABLE  WF_SPOKEN_LANGUAGES ADD CONSTRAINT "WF_CTRY_NUM_FK1" FOREIGN KEY ("COUNTRY_ID")
	REFERENCES  WF_COUNTRIES ("COUNTRY_ID") ENABLE;

ALTER TABLE  WF_SPOKEN_LANGUAGES ADD CONSTRAINT "WF_LANG_ID_FK" FOREIGN KEY ("LANGUAGE_ID")
	REFERENCES  WF_LANGUAGES ("LANGUAGE_ID") ENABLE;
